name: baba-ai
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - tensorflow
  - torch
  - matplotlib
  - pre-commit
  - gym
  - bidict
  - pip:
      - pygame
      - tensorflow-probability
